"""add last_activity_at and blocked_bot to users

Revision ID: 80f98003a322
Revises: eb31f011de33
Create Date: 2026-08-17 00:50:59.170956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f98003a322'
down_revision = 'eb31f011de33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('blocked_bot', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_bot')
    op.drop_column('users', 'last_activity_at')
    # ### end Alembic commands ###
