"""add broadcast_history table

Revision ID: 8b1a98ef6217
Revises: 80f98003a322
Create Date: 2026-08-17 01:06:07.877216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1a98ef6217'
down_revision = '80f98003a322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('media_file_id', sa.String(length=255), nullable=True),
    sa.Column('media_caption', sa.Text(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcast_history')
    # ### end Alembic commands ###
